[package]
name = "phoenix-core"
version = "0.10.0"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
rand_core = "0.6"
dusk-bytes = "0.1"
dusk-bls12_381 = { version = "0.8.0-rc", default-features = false }
dusk-jubjub = { version = "0.10.0-rc", default-features = false }
dusk-poseidon = { version = "0.21.0-rc", default-features = false }
dusk-pki = { version = "0.7.0-rc", default-features = false }
canonical = { version = "0.6", optional = true }
canonical_derive = { version = "0.6", optional = true }

[dev-dependencies]
assert_matches = "1.3"

[features]
canon = [
    "canonical",
    "canonical_derive",
    "dusk-poseidon/canon",
    "dusk-pki/canon"
]

[profile.release]
opt-level = 3
incremental = false
codegen-units = 1
debug = false
lto = true
overflow-checks = false
debug-assertions = false

[profile.dev]
overflow-checks = false
