[package]
name = "phoenix-core"
version = "0.7.0"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
rand_core = "0.5.1"
dusk-bls12_381 = {version = "0.6", default-features = false}
dusk-jubjub = {version = "0.8", default-features = false}
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.16.0", default-features = false}
dusk-pki = {git = "https://github.com/dusk-network/dusk-pki", tag = "v0.5.0", default-features = false}
canonical = {version = "0.5", optional = true}
canonical_derive = {version = "0.5", optional = true}
dusk-bytes = "0.1"

[dev-dependencies]
assert_matches = "1.3"
rand = "0.7"

[features]
canon = [
    "canonical",
    "canonical_derive",
    "poseidon252/canon",
    "dusk-pki/canon"
]

[profile.release]
opt-level = 3
incremental = false
codegen-units = 1
debug = false
lto = true
overflow-checks = false
debug-assertions = false

[profile.dev]
overflow-checks = false
