[package]
name = "phoenix-core"
version = "0.3.1"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
rand = "^0.7"
kelvin = "0.19"
poseidon252 = { git = "https://github.com/dusk-network/Poseidon252", tag = "v0.10.0" }
dusk-pki = { git = "https://github.com/dusk-network/dusk-pki", tag = "v0.2.0" }
thiserror = "1.0"
dusk-plonk = { version = "0.3.1", features = ["trace-print"] }

[dev-dependencies]
assert_matches = "1.3"
anyhow = "1.0.32"

[profile.release]
opt-level = 3
incremental = false
codegen-units = 1
debug = false
lto = true
overflow-checks = false
debug-assertions = false

[profile.dev]
overflow-checks = false
